# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
# set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-logging'
set -g @plugin 'tmux-plugins/tmux-yank'

### Tokyo Night Theme configuration
set -g @theme_variation 'night'
set -g @theme_transparent_status_bar 'true'
set -g @theme_plugins 'datetime'
set -g @theme_left_separator ''
set -g @theme_right_separator ''
set -g @theme_transparent_left_separator_inverse ''
set -g @theme_transparent_right_separator_inverse ''

## Pane Settings
set -g pane-border-status bottom
set -g pane-border-format " [#{pane_index}] "
set -g pane-border-style 'bg=colour240,fg=colour240'
set -g pane-active-border-style 'bg=colour240,fg=colour240'

#### Unbind keys
unbind '"'
unbind %
unbind ","
unbind "."
unbind "<"
unbind Space
unbind ">"
#### 

# Binding configuration
unbind C-b
set -g prefix C-z
bind C-z send-prefix

# Reload
bind R source-file ~/.tmux.conf \; display "Config reloaded"
bind F setw window-size

# History buffer
set -g repeat-time 800
# scrollback history
set -g history-limit 3000

# Command alias
set -sg command-alias[100] quit='kill-window'
set -g renumber-windows off
set -sg command-alias[10] renum='move-window -r'
set -sg command-alias[1] reload='source-file ~/.tmux.conf'
set -sg command-alias[2] sync='set synchronize-panes'
set -sg command-alias[3] wl='setw window-size largest'
set -sg command-alias[4] ws='setw window-size smallest'

# Split a window or pane
bind Space last-window
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind S setw synchronize-panes on
bind s setw synchronize-panes off

#Change layout
bind Enter next-layout
bind u select-layout -o

# move
bind h select-pane -L
bind l select-pane -R
bind k select-pane -U
bind j select-pane -D
# resize
bind -r H resize-pane -L 2
bind -r L resize-pane -R 2
bind -r K resize-pane -U
bind -r J resize-pane -D

# rotate panes
bind -r "," rotate-window -D
bind -r "." rotate-window -U
# swap panes
bind -r "{" swap-pane -U
bind -r "}" swap-pane -D
bind Q resize-pane -Z

# copy mode
setw -g mouse on
setw -g mode-keys vi
set-option -g set-clipboard on

run '~/.tmux/plugins/tpm/tpm'
